server:
  port: 18080
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        lowerCaseServiceId: true  #是将请求路径上的服务名配置为小写
    gateway:
      routes:
        - id: constomer-server #路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:9100     #匹配后提供服务的IP地址 不推荐
          uri: lb://constomer-server #匹配后提供服务的路由地址
          predicates:
            - Path=/constomer-server/**         # 断言，路径相匹配的进行路由
          filters:
          #- StripPrefix=1 #跳过前缀 序号为第几个/
          #- PrefixPath=/auth 添加前缀
        #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION