server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: yaoshun_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


