server:
  port: 8100 # 访问端口
  tomcat:
    uri-encoding: utf-8
    max-threads: 20
    max-connections: 4000
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: constomer-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #可视化连接
        dashboard: 127.0.0.1:8080
        #通信端口
        port: 8719
      #通过json文件提交constomer-server到nacos中 然后sentinel dashboard可以看到持久化配置 关键字sentinel持久化
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            #namespace: c22e5019-0bee-43b1-b80b-fc0b9d847501
            dataId: ${spring.application.name}
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#替换feign底层调用方式 采用http 去除判定body 导致get转换post行为
feign:
  httpclient:
    enabled: true
  #开启对sentinel的支持
  sentinel:
    enabled: true


#用于测试alibaba sentinel->TestController
service-url:
  nacos-user-service: http://producer-server



